### ISSUE TITLE
Text color is not adjusted to relationship status

### ISSUE THREAD

**Issue by iuliailies** [Ozoniuss/clisheer#1]
## Issue description
When adding a debt/expense detail from `Iulia`, the cli doesn't give a way of knowing that the amount of money comes from the girlfriend.

## Steps to reproduce
1. Add a debt
2. Set "Iulia" as person name

## Possible solution
I would expect any interaction with Iulia to have a nice, pink color. Furthermore, a heart should be present somewhere, to make sure you don't forget who the girlfriend is.

**Comment by Ozoniuss** [comment]
Feel free to implement it! You like color and visuals 😵 anyway ...
